export {Home} from "./Home" 
export {Gallery} from "./Gallery" 
export {Contact} from "./Contact" 
export {Navbar} from "./Navbar" 
export {Testimonial} from "./Testimonial" 
export {Highlights} from "./Highlights" 
export {Collage} from "./Collage"